-- WiseLife data architecture: incremental PostgreSQL/Supabase model.
-- This migration is intentionally not executed by v0; review and apply through the project's migration workflow.
-- All CREATE operations are guarded because the connected project already contains production tables.

create schema if not exists private;

-- Authorization source of truth. Never derive authorization from user-editable user_metadata.
create table if not exists public.app_roles (
  code text primary key,
  description text not null,
  created_at timestamptz not null default now(),
  constraint app_roles_code_ck check (code = lower(code) and code ~ '^[a-z][a-z0-9_]{1,63}$')
);

create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_code text not null references public.app_roles(code) on delete restrict,
  granted_at timestamptz not null default now(),
  granted_by uuid references auth.users(id) on delete set null,
  primary key (user_id, role_code)
);

insert into public.app_roles (code, description)
values ('admin', 'Administración de la plataforma'), ('psychologist', 'Profesional clínico'), ('patient', 'Paciente')
on conflict (code) do nothing;

-- Normalize profile referral arrays without removing the legacy column yet.
create table if not exists public.referral_sources (
  id bigint generated by default as identity primary key,
  code text not null unique,
  display_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint referral_sources_code_ck check (code = lower(code) and length(trim(code)) > 0)
);

create table if not exists public.profile_referral_sources (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  referral_source_id bigint not null references public.referral_sources(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (profile_id, referral_source_id)
);

-- Normalize psychologist specialties while retaining psychologists.specialties for compatibility.
create table if not exists public.specialties (
  id bigint generated by default as identity primary key,
  code text not null unique,
  display_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint specialties_code_ck check (code = lower(code) and length(trim(code)) > 0)
);

create table if not exists public.psychologist_specialties (
  psychologist_id uuid not null references public.psychologists(id) on delete cascade,
  specialty_id bigint not null references public.specialties(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (psychologist_id, specialty_id)
);

-- Structured clinical diagnoses; legacy diagnosis fields remain available during migration.
create table if not exists public.session_note_diagnoses (
  session_note_id uuid not null references public.session_notes(id) on delete cascade,
  cie10_code varchar not null references public.cie10_codes(code) on delete restrict,
  diagnosis_order smallint not null default 1,
  is_primary boolean not null default false,
  clinical_description text,
  created_at timestamptz not null default now(),
  primary key (session_note_id, cie10_code),
  constraint session_note_diagnoses_order_ck check (diagnosis_order > 0)
);

create unique index if not exists session_note_one_primary_diagnosis_idx
  on public.session_note_diagnoses (session_note_id)
  where is_primary;

-- Append-only consent history. Current boolean columns remain legacy compatibility fields.
create table if not exists public.consent_events (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles(id) on delete restrict,
  clinical_record_id uuid references public.clinical_records(id) on delete restrict,
  consent_type text not null,
  version text not null,
  accepted boolean not null,
  accepted_at timestamptz not null default now(),
  source text not null default 'web',
  actor_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  constraint consent_events_type_ck check (consent_type in ('informed_consent', 'data_treatment')),
  constraint consent_events_source_ck check (source in ('web', 'admin', 'import', 'api'))
);

-- Immutable audit trail for access/change events on clinical data.
create table if not exists private.clinical_audit_events (
  id bigint generated always as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid references auth.users(id) on delete set null,
  patient_id uuid references public.profiles(id) on delete set null,
  resource_table text not null,
  resource_id uuid,
  action text not null,
  request_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  constraint clinical_audit_action_ck check (action in ('select', 'insert', 'update', 'delete', 'export'))
);

-- Immutable credit ledger; profiles.referral_credits remains a compatibility/cache column.
create table if not exists public.referral_credit_ledger (
  id bigint generated always as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  referral_id uuid references public.referrals(id) on delete restrict,
  delta integer not null,
  reason text not null,
  idempotency_key text not null unique,
  created_at timestamptz not null default now(),
  constraint referral_credit_ledger_delta_ck check (delta <> 0),
  constraint referral_credit_ledger_reason_ck check (length(trim(reason)) > 0)
);

-- Conservative data-quality constraints are installed only when the target objects/columns exist.
do $$
begin
  if to_regclass('public.psychologist_availability') is not null then
    if not exists (select 1 from pg_constraint where conname = 'psychologist_availability_time_ck') then
      alter table public.psychologist_availability add constraint psychologist_availability_time_ck check (start_time < end_time) not valid;
    end if;
  end if;
  if to_regclass('public.schedule_blocks') is not null then
    if not exists (select 1 from pg_constraint where conname = 'schedule_blocks_time_ck') then
      alter table public.schedule_blocks add constraint schedule_blocks_time_ck check (start_time < end_time) not valid;
    end if;
  end if;
  if to_regclass('public.appointments') is not null then
    if not exists (select 1 from pg_constraint where conname = 'appointments_time_ck') then
      alter table public.appointments add constraint appointments_time_ck check (start_time < end_time) not valid;
    end if;
  end if;
end $$;

-- High-cardinality access paths. Existing indexes are preserved by name.
create index if not exists emotional_diary_user_created_idx on public.emotional_diary (user_id, created_at desc);
create index if not exists referrals_referrer_created_idx on public.referrals (referrer_id, created_at desc);
create index if not exists favorite_specialties_user_created_idx on public.favorite_specialties (user_id, created_at desc);
create index if not exists psychologist_availability_lookup_idx on public.psychologist_availability (psychologist_id, day_of_week, start_time) where is_available;
create index if not exists schedule_blocks_lookup_idx on public.schedule_blocks (psychologist_id, block_date, start_time);
create index if not exists appointments_patient_date_idx on public.appointments (patient_id, appointment_date desc, start_time desc);
create index if not exists appointments_psychologist_date_idx on public.appointments (psychologist_id, appointment_date desc, start_time desc);
create index if not exists appointments_status_date_idx on public.appointments (status, appointment_date, start_time);
create index if not exists clinical_records_patient_updated_idx on public.clinical_records (patient_id, updated_at desc);
create index if not exists clinical_records_psychologist_updated_idx on public.clinical_records (psychologist_id, updated_at desc);
create index if not exists session_notes_record_date_idx on public.session_notes (clinical_record_id, session_date desc);
create index if not exists session_notes_patient_date_idx on public.session_notes (patient_id, session_date desc);
create index if not exists session_notes_psychologist_date_idx on public.session_notes (psychologist_id, session_date desc);
create index if not exists payment_transactions_patient_created_idx on public.payment_transactions (patient_id, created_at desc);
create index if not exists payment_transactions_status_created_idx on public.payment_transactions (status, created_at desc);
create index if not exists payment_transactions_nequi_transaction_idx on public.payment_transactions (nequi_transaction_id) where nequi_transaction_id is not null;
create index if not exists clinical_audit_patient_time_idx on private.clinical_audit_events (patient_id, occurred_at desc);
create index if not exists clinical_audit_resource_time_idx on private.clinical_audit_events (resource_table, resource_id, occurred_at desc);
create index if not exists consent_events_patient_time_idx on public.consent_events (patient_id, accepted_at desc);
create index if not exists referral_credit_profile_time_idx on public.referral_credit_ledger (profile_id, created_at desc);
create index if not exists user_roles_role_user_idx on public.user_roles (role_code, user_id);

-- RLS for all new exposed tables. Private audit data is also protected in depth.
alter table public.app_roles enable row level security;
alter table public.user_roles enable row level security;
alter table public.referral_sources enable row level security;
alter table public.profile_referral_sources enable row level security;
alter table public.specialties enable row level security;
alter table public.psychologist_specialties enable row level security;
alter table public.session_note_diagnoses enable row level security;
alter table public.consent_events enable row level security;
alter table public.referral_credit_ledger enable row level security;
alter table private.clinical_audit_events enable row level security;

-- Helper remains in private schema and is not exposed through PostgREST.
create or replace function private.has_app_role(required_role text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.user_roles ur
    where ur.user_id = (select auth.uid()) and ur.role_code = required_role
  );
$$;

revoke all on function private.has_app_role(text) from public;
grant execute on function private.has_app_role(text) to authenticated;

create policy app_roles_select_authenticated on public.app_roles
  for select to authenticated using (true);
create policy user_roles_select_self_or_admin on public.user_roles
  for select to authenticated
  using (user_id = (select auth.uid()) or private.has_app_role('admin'));
create policy user_roles_admin_manage on public.user_roles
  for all to authenticated
  using (private.has_app_role('admin'))
  with check (private.has_app_role('admin'));
create policy referral_sources_select_authenticated on public.referral_sources
  for select to authenticated using (is_active or private.has_app_role('admin'));
create policy profile_referral_sources_self_read on public.profile_referral_sources
  for select to authenticated using (profile_id = (select auth.uid()));
create policy profile_referral_sources_self_write on public.profile_referral_sources
  for all to authenticated
  using (profile_id = (select auth.uid()))
  with check (profile_id = (select auth.uid()));
create policy specialties_select_authenticated on public.specialties
  for select to authenticated using (is_active or private.has_app_role('admin'));
create policy psychologist_specialties_select_authenticated on public.psychologist_specialties
  for select to authenticated using (true);
create policy psychologist_specialties_owner_write on public.psychologist_specialties
  for all to authenticated
  using (exists (select 1 from public.psychologists p where p.id = psychologist_id and p.user_id = (select auth.uid())))
  with check (exists (select 1 from public.psychologists p where p.id = psychologist_id and p.user_id = (select auth.uid())));
create policy session_note_diagnoses_clinical_read on public.session_note_diagnoses
  for select to authenticated
  using (exists (
    select 1 from public.session_notes sn
    where sn.id = session_note_id
      and (sn.patient_id = (select auth.uid()) or exists (
        select 1 from public.psychologists p where p.id = sn.psychologist_id and p.user_id = (select auth.uid())
      ))
  ));
create policy session_note_diagnoses_clinical_write on public.session_note_diagnoses
  for all to authenticated
  using (exists (
    select 1 from public.session_notes sn
    where sn.id = session_note_id
      and exists (select 1 from public.psychologists p where p.id = sn.psychologist_id and p.user_id = (select auth.uid()))
  ))
  with check (exists (
    select 1 from public.session_notes sn
    where sn.id = session_note_id
      and exists (select 1 from public.psychologists p where p.id = sn.psychologist_id and p.user_id = (select auth.uid()))
  ));
create policy consent_events_patient_or_clinician_read on public.consent_events
  for select to authenticated
  using (patient_id = (select auth.uid()) or private.has_app_role('admin') or exists (
    select 1 from public.clinical_records cr join public.psychologists p on p.id = cr.psychologist_id
    where cr.id = clinical_record_id and p.user_id = (select auth.uid())
  ));
create policy consent_events_patient_insert on public.consent_events
  for insert to authenticated
  with check (patient_id = (select auth.uid()) and actor_id = (select auth.uid()));
create policy referral_credit_ledger_self_read on public.referral_credit_ledger
  for select to authenticated using (profile_id = (select auth.uid()));
create policy clinical_audit_admin_read on private.clinical_audit_events
  for select to authenticated using (private.has_app_role('admin'));

-- End users must not mutate ledger/audit rows directly.
revoke insert, update, delete on public.referral_credit_ledger from anon, authenticated;
revoke insert, update, delete on private.clinical_audit_events from anon, authenticated;

comment on table public.profile_referral_sources is '3NF bridge for profile referral sources; profiles.referral_sources is legacy compatibility.';
comment on table public.psychologist_specialties is '3NF bridge for psychologist specialties; psychologists.specialties is legacy compatibility.';
comment on table public.session_note_diagnoses is 'Normalized diagnosis relation for clinical session notes.';
comment on table public.consent_events is 'Append-only consent history; current consent booleans in clinical_records are legacy compatibility.';
comment on table private.clinical_audit_events is 'Append-only clinical access/change audit log; partition by occurred_at when volume requires it.';
comment on table public.referral_credit_ledger is 'Immutable referral credit ledger; profiles.referral_credits is a derived compatibility cache.';
